Nm_erro = {
  "lang_jscr_dcml" : "Decimali",
  "lang_jscr_decm" : "Decimo di secondo",
  "lang_jscr_hour" : "Ora",
  "lang_jscr_iday" : "Giorno",
  "lang_jscr_intg" : "Numeri interi e",
  "lang_jscr_ivcr" : "Numero di carta di credito non valido",
  "lang_jscr_ivdt" : "Dati non validi:",
  "lang_jscr_ivem" : "E-mail non valida",
  "lang_jscr_ivnb" : "Numero intero non valido",
  "lang_jscr_ivtm" : "Ora non valida:",
  "lang_jscr_ivv2" : "Dati non validi:",
  "lang_jscr_ivvl" : "Decimale non valido",
  "lang_jscr_maxm" : "Max",
  "lang_jscr_maxm_date" : "Data massima",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Data minima",
  "lang_jscr_mint" : "Minuti",
  "lang_jscr_mnth" : "Mese",
  "lang_jscr_msfr" : "Il modulo deve avere un nome",
  "lang_jscr_mslg" : "Nome utente mancante;",
  "lang_jscr_msob" : "Questo oggetto Form deve avere un nome",
  "lang_jscr_mxdg" : "Il numero di cifre supera il limite",
  "lang_jscr_mxvl" : "Lunghezza massima superata",
  "lang_jscr_nnum" : "Il campo è numerico",
  "lang_jscr_nvlf" : "Il segno negativo deve essere a sinistra del valore",
  "lang_jscr_reqr" : "Campo obbligatorio",
  "lang_jscr_secd" : "Secondi",
  "lang_jscr_wfix" : "- vuoi correggerlo?"
};

//-------- Mens USR
