Nm_erro = {
  "lang_jscr_dcml" : "Dezimalstellen",
  "lang_jscr_decm" : "Zehntelsekunde",
  "lang_jscr_hour" : "Stunde",
  "lang_jscr_iday" : "Tag",
  "lang_jscr_intg" : "Ganzzahlen und",
  "lang_jscr_ivcr" : "Ungültige Kreditkartennummer",
  "lang_jscr_ivdt" : "Ungültige Daten:",
  "lang_jscr_ivem" : "Ungültige E-Mail",
  "lang_jscr_ivnb" : "Ungültige Ganzzahl",
  "lang_jscr_ivtm" : "Ungültige Zeit:",
  "lang_jscr_ivv2" : "Ungültige Daten:",
  "lang_jscr_ivvl" : "Ungültige Dezimalstelle",
  "lang_jscr_maxm" : "Maximum",
  "lang_jscr_maxm_date" : "Maximales Datum",
  "lang_jscr_minm" : "Minimum",
  "lang_jscr_minm_date" : "Mindestdatum",
  "lang_jscr_mint" : "Minuten",
  "lang_jscr_mnth" : "Monat",
  "lang_jscr_msfr" : "Das Formular muss einen Namen haben",
  "lang_jscr_mslg" : "Benutzername fehlt;",
  "lang_jscr_msob" : "Bitte einen Namen für das Formular eingeben",
  "lang_jscr_mxdg" : "Die Anzahl der Stellen überschreitet den Grenzwert",
  "lang_jscr_mxvl" : "Maximale Länge überschritten",
  "lang_jscr_nnum" : "Das Feld ist numerisch",
  "lang_jscr_nvlf" : "Das negative Vorzeichen muss links vom Wert stehen",
  "lang_jscr_reqr" : "Pflichtfeld",
  "lang_jscr_secd" : "Sekunden",
  "lang_jscr_wfix" : "- Möchten Sie dies korrigieren?"
};

//-------- Mens USR
