Nm_erro = {
  "lang_jscr_dcml" : "Decimais",
  "lang_jscr_decm" : "Décimos de segundo",
  "lang_jscr_hour" : "Hora",
  "lang_jscr_iday" : "Dia",
  "lang_jscr_intg" : "Inteiros e",
  "lang_jscr_ivcr" : "Cartão Inválido",
  "lang_jscr_ivdt" : "Dados Inválidos:",
  "lang_jscr_ivem" : "Email Inválido:",
  "lang_jscr_ivnb" : "Número Inválido",
  "lang_jscr_ivtm" : "Hora Inválida:",
  "lang_jscr_ivv2" : "Valor Inválido:",
  "lang_jscr_ivvl" : "Valor Inválido",
  "lang_jscr_maxm" : "Max",
  "lang_jscr_maxm_date" : "Data máxima",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Data mínima",
  "lang_jscr_mint" : "Minutos",
  "lang_jscr_mnth" : "Mês",
  "lang_jscr_msfr" : "Definir um nome para o formulário",
  "lang_jscr_mslg" : "Faltou Login;",
  "lang_jscr_msob" : "Definir um nome para este formulário",
  "lang_jscr_mxdg" : "Foi excedida a quantidade de dígitos",
  "lang_jscr_mxvl" : "Valor máximo ultrapassado",
  "lang_jscr_nnum" : "Campo com dados não numéricos",
  "lang_jscr_nvlf" : "O sinal negativo deve ficar à esquerda do valor",
  "lang_jscr_reqr" : "Campos obrigatórios",
  "lang_jscr_secd" : "Segundos",
  "lang_jscr_wfix" : "- Deseja corrigir?"
};

//-------- Mens USR
